
package com.epam.lab.client.soap.service.sources;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SOAPCalculator", targetNamespace = "http://soap.lab.epam.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SOAPCalculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.lab.epam.com/SOAPCalculator/addRequest", output = "http://soap.lab.epam.com/SOAPCalculator/addResponse")
    public String add(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.lab.epam.com/SOAPCalculator/divideRequest", output = "http://soap.lab.epam.com/SOAPCalculator/divideResponse")
    public String divide(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.lab.epam.com/SOAPCalculator/multiplyRequest", output = "http://soap.lab.epam.com/SOAPCalculator/multiplyResponse")
    public String multiply(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.lab.epam.com/SOAPCalculator/subtractRequest", output = "http://soap.lab.epam.com/SOAPCalculator/subtractResponse")
    public String subtract(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.lab.epam.com/SOAPCalculator/getNumberPercentageRequest", output = "http://soap.lab.epam.com/SOAPCalculator/getNumberPercentageResponse")
    public String getNumberPercentage(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

}
